apiVersion: v1
kind: Secret
metadata:
  name: rustfs-credentials
  namespace: storage
  labels:
    app.kubernetes.io/name: rustfs
type: Opaque
stringData:
  RUSTFS_ACCESS_KEY: rustfsadmin
  RUSTFS_SECRET_KEY: rustfsadmin
