apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rustfs
  namespace: storage
  labels:
    app.kubernetes.io/name: rustfs
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: rustfs.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rustfs
                port:
                  number: 9000
    - host: rustfs-console.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rustfs
                port:
                  number: 9001
