apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: storage

resources:
  - 00-namespace.yaml
  - 10-secret.yaml
  - 20-service.yaml
  - 30-statefulset.yaml
  - 40-ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: world-forge
