apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vuejs-template
  namespace: vuejs
  labels:
    app.kubernetes.io/name: vuejs-template
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: vuejs-template
