apiVersion: v1
kind: Namespace
metadata:
  name: world
  labels:
    app.kubernetes.io/name: world-forge
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
