apiVersion: v1
kind: Secret
metadata:
  name: artemis-credentials
  namespace: broker
  labels:
    app.kubernetes.io/name: artemis
type: Opaque
stringData:
  ARTEMIS_USER: artemis
  ARTEMIS_PASSWORD: artemis
